---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.less"
  - "**.js"
  - "**.php"
exclude_paths:
- config/
engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true

exclude_paths:
- "tests/**/*"
- "vendor/**/*"
